// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Z_7jfeohKTUukIFu_pqJmQFfwL-OkSg',
    appId: '1:795158235715:web:d8665411844e82b30362f6',
    messagingSenderId: '795158235715',
    projectId: 'shopping-c344b',
    authDomain: 'shopping-c344b.firebaseapp.com',
    storageBucket: 'shopping-c344b.appspot.com',
    measurementId: 'G-PDBMMJ3LHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUPuCNw8f8wbdmluAJn1sUyNyBJdOC_48',
    appId: '1:795158235715:android:43e06c78b11a711c0362f6',
    messagingSenderId: '795158235715',
    projectId: 'shopping-c344b',
    storageBucket: 'shopping-c344b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOQhP-G0uwUwcepaUOnsRAcFmZaOBxo-0',
    appId: '1:795158235715:ios:99c1fd26e62ae3420362f6',
    messagingSenderId: '795158235715',
    projectId: 'shopping-c344b',
    storageBucket: 'shopping-c344b.appspot.com',
    iosClientId: '795158235715-364n8ragaj7d5h587inn6c5darui4h1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingCentre',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOQhP-G0uwUwcepaUOnsRAcFmZaOBxo-0',
    appId: '1:795158235715:ios:99c1fd26e62ae3420362f6',
    messagingSenderId: '795158235715',
    projectId: 'shopping-c344b',
    storageBucket: 'shopping-c344b.appspot.com',
    iosClientId: '795158235715-364n8ragaj7d5h587inn6c5darui4h1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingCentre',
  );
}
